### ISSUE TITLE
Exception: No matching checkpoint file found

### ISSUE THREAD

**Issue by prsnkmr** [byminji/SLTtrack#3]
After going through this link   https://github.com/visionml/pytracking.git , i duplicate the run_video.py when i running it is throwing an error like shown below. will anybody help me from this ,thanks in advance

slt) T7751P1@ubncnd2203bjf:~/Downloads/SLTtrack$ python pytracking/run_video.py slt_transt  slt_transt  VIDEO_for_sot.mp4 --save_results
Traceback (most recent call last):
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/run_video.py", line 38, in <module>
    main()
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/evaluation/tracker.py", line 257, in run_video
    tracker = MultiObjectWrapper(self.tracker_class, params, self.visdom, fast_load=True)
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/evaluation/multi_object_wrapper.py", line 20, in __init__
    self.tracker_copy.initialize_features()
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/tracker/slt_transt/slt_transt.py", line 45, in initialize_features
    self.params.net.initialize()
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/features/net_wrappers.py", line 53, in initialize
    super().initialize()
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/features/net_wrappers.py", line 37, in initialize
    self.load_network()
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/features/net_wrappers.py", line 31, in load_network
    self.net = load_network(self.net_path, **self.net_kwargs)
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../pytracking/utils/loading.py", line 31, in load_network
    net, _ = ltr_loading.load_network(path_full, **kwargs)
  File "/home/T7751P1/Downloads/SLTtrack/pytracking/../ltr/admin/loading.py", line 62, in load_network
    raise Exception('No matching checkpoint file found')

**Comment by byminji** [comment]
Please refer to our docs and save the model checkpoint file in your local path. Thanks.
