### ISSUE TITLE
Is it possible to train on a smaller GPU?

### ISSUE THREAD

**Issue by ghost** [byminji/SLTtrack#8]
Hi,

I am attempting to train on either the TransT or TrDiMP models but I keep getting this error.

`
Using CuDNN Benchmark
Training:  slt_transt  slt_transt
WARNING: You are using tensorboardX instead sis you have a too old pytorch version.
number of params: 23016006
No matching checkpoint file found
Backend TkAgg is interactive backend. Turning interactive mode on.
Training crashed at epoch 1
Traceback for the error!

Traceback (most recent call last):
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/trainers/slt_transt_trainer.py", line 150, in train_epoch
    self.cycle_dataset(loader)
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/trainers/slt_transt_trainer.py", line 62, in cycle_dataset
    explore_result = self.actor.explore(data)
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/actors/slt_transt_actor.py", line 82, in explore
    outputs = tracker.batch_track(here_images, here_gt_bbox, action_mode='half')
  File "/home/usr/Classes/RL/SLTtrack/ltr/../pytracking/tracker/slt_transt/slt_transt.py", line 143, in batch_track
    outputs = self.net.track_batch(x_crop)
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/models/tracking/transt.py", line 115, in track_batch
    hs = self.featurefusion_network(self.input_proj(src_template), mask_template, self.input_proj(src_search), mask_search, self.pos_template[-1], pos_search[-1])
  File "/home/usr/miniconda3/envs/slt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/models/neck/featurefusion_network.py", line 53, in forward
    hs = self.decoder(memory_search, memory_temp,
  File "/home/usr/miniconda3/envs/slt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/models/neck/featurefusion_network.py", line 77, in forward
    output = layer(output, memory, tgt_mask=tgt_mask,
  File "/home/usr/miniconda3/envs/slt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/models/neck/featurefusion_network.py", line 165, in forward
    return self.forward_post(tgt, memory, tgt_mask, memory_mask,
  File "/home/usr/Classes/RL/SLTtrack/ltr/../ltr/models/neck/featurefusion_network.py", line 151, in forward_post
    tgt2 = self.linear2(self.dropout(self.activation(self.linear1(tgt))))
  File "/home/usr/miniconda3/envs/slt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/usr/miniconda3/envs/slt/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/usr/miniconda3/envs/slt/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)

RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 15.72 GiB total capacity; 11.81 GiB already allocated; 66.81 MiB free; 11.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

I have set `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512` to try to manage memory as suggested, but I get the same error. I am running on Ubuntu 22.04, and using an NVIDIA RTX 3080 Ti which has 16GB RAM.  I haven't currently found any, but was wondering if there are any hyperparameters I can change in order to allow training to happen (however slow that may be).

**Comment by byminji** [comment]
Hi, basically we used 1 NVIDIA A6000 GPU with 48GB RAM. I haven't tried but you could change `settings.num_seq_backward` in [this file](https://github.com/byminji/SLTtrack/blob/master/ltr/train_settings/slt_transt/slt_transt.py). `num_seq_backward` means the number of video sequences that we calculate the gradients at once. Then we accumulate the gradients for total `num_seq` videos and step the optimizer. Decreasing `num_seq_backward` would make the training slow but would be helpful for reducing memory consumption.
